name: Full CICD Test

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Start Docker Compose Services
      run: |
        docker-compose up -d

    - name: Wait for Services to Start
      run: sleep 30

    - name: Check Service Status
      run: |
        docker-compose -f docker-compose.yml ps

    - name: Test Docker Registry
      run: |
        curl -u user:password http://localhost:5000/v2/  # Adjust port and auth as necessary

    - name: Test PyPI Server
      run: |
        curl http://localhost:8080/  # Adjust port as necessary

    - name: Clean up
      run: |
        docker-compose -f docker-compose.yml down
